---
- name: copy gps_on_off
  copy:
    src: gps_on_off
    dest: /usr/local/bin/gps_on_off
    owner: root
    group: root
    mode: 0755

- name: change owner for gps location.conf
  file:
    path: /etc/location/location.conf
    owner: "nemo"
    group: "privileged"
